from django.urls import path,include
from .views import register, login, adminDashboard, approveUser, disapproveUser, Department, personal, workPage, experiencePage, educationPage, bankPage, AddDepartment, AddDepartmentSuccess, EditDepartment, DeleteDepartment, DesignationTable, AddDesignation, AddDesignationSuccess, DeleteDesignation, EditDesignation, RoleTable, AddRoleSuccess, AddRole, EditRole, DeleteRole, LeaveTypeTable, AddLeaveTypeSuccess, AddLeaveType, EditLeaveType, DeleteLeaveType, LeaveManagerTable, ApplyLeavePage, HolidayListTable, AddHolidayListSuccess, AddHolidayList, EditHolidayList, DeleteHolidayList, EmployeeTable, EmployeeDetailTable, ApproveEmployeeTable, ApproveEmployeeSuccess, ApproveEmployeeLeaveTable, ApproveEmployeeLeaveSuccess, approveLeave, LeaveAppliedTable, logout, profile, passwordChange, adminDashboardNotAllowed


urlpatterns = [
    path('register/', register),
    path('login/', login),
    path('logout/', logout),
    path('change-password/', passwordChange, name="change password"),
    path('dashboard/', adminDashboard, name="dashboard"),
    path('dashboard/<str:success>/', adminDashboardNotAllowed, name="dashboard"),
    path('approve/<int:id>/', approveUser),
    path('disapprove/<int:id>/', disapproveUser),
    path('profile/', profile, name="update profile"),
    path('profile/personal/', personal, name="personal"),
    path('profile/work/', workPage, name="work"),
    path('profile/experience/', experiencePage, name="experience"),
    path('profile/education/', educationPage, name="education"),
    path('profile/bank/', bankPage, name="bank"),
    path('setting/department/', Department, name="department"),
    path('setting/department/manage/<str:success>/', AddDepartmentSuccess, name="department"),
    path('setting/department/add/', AddDepartment, name="department"),
    path('setting/department/edit/<str:pk>/', EditDepartment, name="department"),
    path('setting/department/delete/<str:pk>/', DeleteDepartment),
    path('setting/designation/', DesignationTable, name="designation"),
    path('setting/designation/manage/<str:success>/', AddDesignationSuccess, name="designation"),
    path('setting/designation/add/', AddDesignation, name="designation"),
    path('setting/designation/delete/<str:pk>/', DeleteDesignation),
    path('setting/designation/edit/<str:pk>/', EditDesignation, name="designation"),
    path('setting/role/', RoleTable, name="role"),
    path('setting/role/manage/<str:success>/', AddRoleSuccess, name="role"),
    path('setting/role/add/', AddRole, name="role"),
    path('setting/role/delete/<str:pk>/', DeleteRole),
    path('setting/role/edit/<str:pk>/', EditRole, name="role"),
    path('setting/leavetype/', LeaveTypeTable, name="leavetype"),
    path('setting/leavetype/manage/<str:success>/', AddLeaveTypeSuccess, name="leavetype"),
    path('setting/leavetype/add/', AddLeaveType, name="leavetype"),
    path('setting/leavetype/delete/<str:pk>/', DeleteLeaveType),
    path('setting/leavetype/edit/<str:pk>/', EditLeaveType, name="leavetype"),
    path('leavemanager/', LeaveManagerTable, name="leavemanager"),
    path('leavemanager/apply/', ApplyLeavePage, name="leavemanager"),
    path('setting/holiday/', HolidayListTable, name="holiday"),
    path('setting/holiday/manage/<str:success>/', AddHolidayListSuccess, name="holiday"),
    path('setting/holiday/add/', AddHolidayList, name="holiday"),
    path('setting/holiday/delete/<str:pk>/', DeleteHolidayList),
    path('setting/holiday/edit/<str:pk>/', EditHolidayList, name="holiday"),
    path('employees/', EmployeeTable, name="employee"),
    path('employees/view/<str:pk>/', EmployeeDetailTable, name="employee"),
    path('new-employees/', ApproveEmployeeTable, name="newemployee"),
    path('new-employees/manage/<str:success>/', ApproveEmployeeSuccess, name="newemployee"),
    path('leave-verify/', ApproveEmployeeLeaveTable, name="leaveverify"),
    path('leave-verify/manage/<str:success>/', ApproveEmployeeLeaveSuccess, name="leaveverify"),
    path('leave-verify/approve/<int:id>/', approveLeave, name="leaveverify"),
    path('leaveapplied/', LeaveAppliedTable, name="leaveapplied"),
    
    
]