# Generated by Django 3.2 on 2021-04-29 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Leave_Type', models.CharField(choices=[('PD', 'Paid'), ('UD', 'Unpaid'), ('OD', 'On Duty'), ('RH', 'Restricted Holiday')], default='UD', max_length=2)),
                ('Unit', models.CharField(choices=[('DY', 'Days'), ('HR', 'Hours')], default='DY', max_length=2)),
                ('Description', models.TextField(default='')),
                ('Valid_From', models.DateField(default=django.utils.timezone.now)),
                ('Valid_To', models.DateField(default=django.utils.timezone.now)),
                ('Opening_Balance', models.CharField(max_length=50)),
                ('Closing_Balance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valid_From', models.DateField(default=django.utils.timezone.now)),
                ('Valid_To', models.DateField(default=django.utils.timezone.now)),
                ('Team_Email_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('Reason_For_Leave', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Leave_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.leavetype')),
            ],
        ),
    ]
