# Generated by Django 3.2 on 2021-05-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='Closing_Balance',
            new_name='Maximum_Balance',
        ),
    ]
