# Generated by Django 3.2 on 2021-05-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_rename_closing_balance_leavetype_maximum_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='Description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
