# Generated by Django 3.2 on 2021-05-10 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0004_leaveavailable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveavailable',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveavailable',
            name='leaveAvailable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leaveavailable',
            name='leavetype',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
        ),
    ]
