# Generated by Django 3.2 on 2021-05-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_alter_leaveavailable_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='Holiday_Between_Leave_Period',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='Maximum_Number_Of_Consecutive_Days_Of_Leave_Allowed',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='Minimum_Gap_Between_2_Application_In_Days',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='To_Be_Applied_Days_In_Advance',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
