# Generated by Django 3.2 on 2021-05-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_applyleave_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleave',
            name='Reason_For_Rejection',
            field=models.TextField(default=''),
        ),
    ]
