# Generated by Django 3.2 on 2021-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_applyleave_reason_for_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyleave',
            name='Rejected',
            field=models.BooleanField(default=False),
        ),
    ]
