# Generated by Django 3.2 on 2021-04-29 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designation', '__first__'),
        ('roles', '__first__'),
        ('UserAuth', '__first__'),
        ('department', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_Of_Joining', models.DateField(default=django.utils.timezone.now)),
                ('Employee_Status', models.CharField(choices=[('AV', 'Active'), ('TM', 'Terminated'), ('DS', 'Deceased'), ('RN', 'Resigned')], default='AV', max_length=2)),
                ('Employee_Type', models.CharField(choices=[('PM', 'Permanent'), ('OC', 'On Contract'), ('TP', 'Temporary'), ('TR', 'Trainee')], default='TR', max_length=2)),
                ('Work_Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Extension', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Department', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='department.department')),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('Reporting_To', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting', to=settings.AUTH_USER_MODEL)),
                ('Role', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.roles')),
                ('Source_Of_Hire', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to=settings.AUTH_USER_MODEL)),
                ('Title', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_title', to='designation.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile_Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Other_Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Date_Of_Birth', models.DateField(default=django.utils.timezone.now)),
                ('MARITAL_STATUS', models.CharField(choices=[('SG', 'Single'), ('MD', 'Married')], default='SG', max_length=2)),
                ('Gender', models.CharField(choices=[('ML', 'Male'), ('FL', 'Female')], default='ML', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('UserApproved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserAuth.userapproved')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Previous_Company_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Job_Title', models.CharField(blank=True, max_length=50, null=True)),
                ('From', models.DateField(default=django.utils.timezone.now)),
                ('To', models.DateField(default=django.utils.timezone.now)),
                ('Job_Description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Degree_Or_Diploma', models.CharField(blank=True, max_length=50, null=True)),
                ('Field_Of_Study', models.CharField(blank=True, max_length=50, null=True)),
                ('Date_Of_Completion', models.DateField(default=django.utils.timezone.now)),
                ('Interests', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Account_Number', models.CharField(blank=True, max_length=50, null=True)),
                ('Branch_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('IFSC_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
