# Generated by Django 3.2 on 2021-04-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0001_initial'),
        ('employee', '0006_remove_personal_userapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='userApproved',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved', to='UserAuth.userapproved'),
        ),
    ]
