# Generated by Django 3.2 on 2021-04-29 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_personal_userapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='userApproved',
        ),
    ]
