# Generated by Django 3.2 on 2021-05-08 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
        ('designation', '0001_initial'),
        ('roles', '0001_initial'),
        ('employee', '0010_alter_personal_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='Employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='Employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_education', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_experience', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='Department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department', to='department.department'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Reporting_To',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='Role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.roles'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Source_Of_Hire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='work',
            name='Title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_title', to='designation.designation'),
        ),
    ]
